FROM node:14-alpine3.12
RUN npm install -g @nestjs/cli
WORKDIR /home/app

# COPY ./server/package.json .
# COPY ./server/package-lock.json .
# RUN npm install

# COPY ./server .
# CMD [ "npm", "run", "start:dev"]
